let countryList = [

	{
		name: "Wallis and Futuna",
		capital: "Mata-Utu",
		code: "681",
		flag: "https://restcountries.eu/data/wlf.svg",
	},
	{
		name: "Afghanistan",
		capital: "Kabul",
		code: "93",
		flag: "https://restcountries.eu/data/afg.svg",
	},
	{
		name: "Albania",
		capital: "Tirana",
		code: "355",
		flag: "https://restcountries.eu/data/alb.svg",
	},
	{
		name: "Algeria",
		capital: "Algiers",
		code: "213",
		flag: "https://restcountries.eu/data/dza.svg",
	},
	{
		name: "American Samoa",
		capital: "Pago Pago",
		code: "1684",
		flag: "https://restcountries.eu/data/asm.svg",
	},
	{
		name: "Andorra",
		capital: "Andorra la Vella",
		code: "376",
		flag: "https://restcountries.eu/data/and.svg",
	},
	{
		name: "Angola",
		capital: "Luanda",
		code: "244",
		flag: "https://restcountries.eu/data/ago.svg",
	},
	{
		name: "Anguilla",
		capital: "The Valley",
		code: "1264",
		flag: "https://restcountries.eu/data/aia.svg",
	},
	{
		name: "Antarctica",
		capital: "",
		code: "672",
		flag: "https://restcountries.eu/data/ata.svg",
	},
	{
		name: "Antigua and Barbuda",
		capital: "Saint John's",
		code: "1268",
		flag: "https://restcountries.eu/data/atg.svg",
	},
	{
		name: "Argentina",
		capital: "Buenos Aires",
		code: "54",
		flag: "https://restcountries.eu/data/arg.svg",
	},
	{
		name: "Armenia",
		capital: "Yerevan",
		code: "374",
		flag: "https://restcountries.eu/data/arm.svg",
	},
	{
		name: "Aruba",
		capital: "Oranjestad",
		code: "297",
		flag: "https://restcountries.eu/data/abw.svg",
	},
	{
		name: "Australia",
		capital: "Canberra",
		code: "61",
		flag: "https://restcountries.eu/data/aus.svg",
	},
	{
		name: "Austria",
		capital: "Vienna",
		code: "43",
		flag: "https://restcountries.eu/data/aut.svg",
	},
	{
		name: "Azerbaijan",
		capital: "Baku",
		code: "994",
		flag: "https://restcountries.eu/data/aze.svg",
	},
	{
		name: "Bahamas",
		capital: "Nassau",
		code: "1242",
		flag: "https://restcountries.eu/data/bhs.svg",
	},
	{
		name: "Bahrain",
		capital: "Manama",
		code: "973",
		flag: "https://restcountries.eu/data/bhr.svg",
	},
	{
		name: "Bangladesh",
		capital: "Dhaka",
		code: "880",
		flag: "https://restcountries.eu/data/bgd.svg",
	},
	{
		name: "Barbados",
		capital: "Bridgetown",
		code: "1246",
		flag: "https://restcountries.eu/data/brb.svg",
	},
	{
		name: "Belarus",
		capital: "Minsk",
		code: "375",
		flag: "https://restcountries.eu/data/blr.svg",
	},
	{
		name: "Belgium",
		capital: "Brussels",
		code: "32",
		flag: "https://restcountries.eu/data/bel.svg",
	},
	{
		name: "Belize",
		capital: "Belmopan",
		code: "501",
		flag: "https://restcountries.eu/data/blz.svg",
	},
	{
		name: "Benin",
		capital: "Porto-Novo",
		code: "229",
		flag: "https://restcountries.eu/data/ben.svg",
	},
	{
		name: "Bermuda",
		capital: "Hamilton",
		code: "1441",
		flag: "https://restcountries.eu/data/bmu.svg",
	},
	{
		name: "Bhutan",
		capital: "Thimphu",
		code: "975",
		flag: "https://restcountries.eu/data/btn.svg",
	},
	{
		name: "Bolivia (Plurinational State of)",
		capital: "Sucre",
		code: "591",
		flag: "https://restcountries.eu/data/bol.svg",
	},
	{
		name: "Bonaire, Sint Eustatius and Saba",
		capital: "Kralendijk",
		code: "5997",
		flag: "https://restcountries.eu/data/bes.svg",
	},
	{
		name: "Bosnia and Herzegovina",
		capital: "Sarajevo",
		code: "387",
		flag: "https://restcountries.eu/data/bih.svg",
	},
	{
		name: "Botswana",
		capital: "Gaborone",
		code: "267",
		flag: "https://restcountries.eu/data/bwa.svg",
	},

	{
		name: "Brazil",
		capital: "Brasília",
		code: "55",
		flag: "https://restcountries.eu/data/bra.svg",
	},
	{
		name: "British Indian Ocean Territory",
		capital: "Diego Garcia",
		code: "246",
		flag: "https://restcountries.eu/data/iot.svg",
	},
	{
		name: "Brunei Darussalam",
		capital: "Bandar Seri Begawan",
		code: "673",
		flag: "https://restcountries.eu/data/brn.svg",
	},
	{
		name: "Bulgaria",
		capital: "Sofia",
		code: "359",
		flag: "https://restcountries.eu/data/bgr.svg",
	},
	{
		name: "Burkina Faso",
		capital: "Ouagadougou",
		code: "226",
		flag: "https://restcountries.eu/data/bfa.svg",
	},
	{
		name: "Burundi",
		capital: "Bujumbura",
		code: "257",
		flag: "https://restcountries.eu/data/bdi.svg",
	},
	{
		name: "Cambodia",
		capital: "Phnom Penh",
		code: "855",
		flag: "https://restcountries.eu/data/khm.svg",
	},
	{
		name: "Cameroon",
		capital: "Yaoundé",
		code: "237",
		flag: "https://restcountries.eu/data/cmr.svg",
	},
	{
		name: "Canada",
		capital: "Ottawa",
		code: "1",
		flag: "https://restcountries.eu/data/can.svg",
	},
	{
		name: "Cabo Verde",
		capital: "Praia",
		code: "238",
		flag: "https://restcountries.eu/data/cpv.svg",
	},
	{
		name: "Cayman Islands",
		capital: "George Town",
		code: "1345",
		flag: "https://restcountries.eu/data/cym.svg",
	},
	{
		name: "Central African Republic",
		capital: "Bangui",
		code: "236",
		flag: "https://restcountries.eu/data/caf.svg",
	},
	{
		name: "Chad",
		capital: "N'Djamena",
		code: "235",
		flag: "https://restcountries.eu/data/tcd.svg",
	},
	{
		name: "Chile",
		capital: "Santiago",
		code: "56",
		flag: "https://restcountries.eu/data/chl.svg",
	},
	{
		name: "China",
		capital: "Beijing",
		code: "86",
		flag: "https://restcountries.eu/data/chn.svg",
	},
	{
		name: "Christmas Island",
		capital: "Flying Fish Cove",
		code: "61",
		flag: "https://restcountries.eu/data/cxr.svg",
	},
	{
		name: "Cocos (Keeling) Islands",
		capital: "West Island",
		code: "61",
		flag: "https://restcountries.eu/data/cck.svg",
	},
	{
		name: "Colombia",
		capital: "Bogotá",
		code: "57",
		flag: "https://restcountries.eu/data/col.svg",
	},
	{
		name: "Comoros",
		capital: "Moroni",
		code: "269",
		flag: "https://restcountries.eu/data/com.svg",
	},
	{
		name: "Congo",
		capital: "Brazzaville",
		code: "242",
		flag: "https://restcountries.eu/data/cog.svg",
	},
	{
		name: "Congo (Democratic Republic of the)",
		capital: "Kinshasa",
		code: "243",
		flag: "https://restcountries.eu/data/cod.svg",
	},
	{
		name: "Cook Islands",
		capital: "Avarua",
		code: "682",
		flag: "https://restcountries.eu/data/cok.svg",
	},
	{
		name: "Costa Rica",
		capital: "San José",
		code: "506",
		flag: "https://restcountries.eu/data/cri.svg",
	},
	{
		name: "Croatia",
		capital: "Zagreb",
		code: "385",
		flag: "https://restcountries.eu/data/hrv.svg",
	},
	{
		name: "Cuba",
		capital: "Havana",
		code: "53",
		flag: "https://restcountries.eu/data/cub.svg",
	},
	{
		name: "Curaçao",
		capital: "Willemstad",
		code: "599",
		flag: "https://restcountries.eu/data/cuw.svg",
	},
	{
		name: "Cyprus",
		capital: "Nicosia",
		code: "357",
		flag: "https://restcountries.eu/data/cyp.svg",
	},
	{
		name: "Czech Republic",
		capital: "Prague",
		code: "420",
		flag: "https://restcountries.eu/data/cze.svg",
	},
	{
		name: "Denmark",
		capital: "Copenhagen",
		code: "45",
		flag: "https://restcountries.eu/data/dnk.svg",
	},
	{
		name: "Djibouti",
		capital: "Djibouti",
		code: "253",
		flag: "https://restcountries.eu/data/dji.svg",
	},
	{
		name: "Dominica",
		capital: "Roseau",
		code: "1767",
		flag: "https://restcountries.eu/data/dma.svg",
	},
	{
		name: "Dominican Republic",
		capital: "Santo Domingo",
		code: "1809",
		flag: "https://restcountries.eu/data/dom.svg",
	},
	{
		name: "Ecuador",
		capital: "Quito",
		code: "593",
		flag: "https://restcountries.eu/data/ecu.svg",
	},
	{
		name: "Egypt",
		capital: "Cairo",
		code: "20",
		flag: "https://restcountries.eu/data/egy.svg",
	},
	{
		name: "El Salvador",
		capital: "San Salvador",
		code: "503",
		flag: "https://restcountries.eu/data/slv.svg",
	},
	{
		name: "Equatorial Guinea",
		capital: "Malabo",
		code: "240",
		flag: "https://restcountries.eu/data/gnq.svg",
	},
	{
		name: "Eritrea",
		capital: "Asmara",
		code: "291",
		flag: "https://restcountries.eu/data/eri.svg",
	},
	{
		name: "Estonia",
		capital: "Tallinn",
		code: "372",
		flag: "https://restcountries.eu/data/est.svg",
	},
	{
		name: "Ethiopia",
		capital: "Addis Ababa",
		code: "251",
		flag: "https://restcountries.eu/data/eth.svg",
	},
	{
		name: "Falkland Islands (Malvinas)",
		capital: "Stanley",
		code: "500",
		flag: "https://restcountries.eu/data/flk.svg",
	},
	{
		name: "Faroe Islands",
		capital: "Tórshavn",
		code: "298",
		flag: "https://restcountries.eu/data/fro.svg",
	},
	{
		name: "Fiji",
		capital: "Suva",
		code: "679",
		flag: "https://restcountries.eu/data/fji.svg",
	},
	{
		name: "Finland",
		capital: "Helsinki",
		code: "358",
		flag: "https://restcountries.eu/data/fin.svg",
	},
	{
		name: "France",
		capital: "Paris",
		code: "33",
		flag: "https://restcountries.eu/data/fra.svg",
	},
	{
		name: "French Guiana",
		capital: "Cayenne",
		code: "594",
		flag: "https://restcountries.eu/data/guf.svg",
	},
	{
		name: "French Polynesia",
		capital: "Papeetē",
		code: "689",
		flag: "https://restcountries.eu/data/pyf.svg",
	},
	{
		name: "French Southern Territories",
		capital: "Port-aux-Français",
		code: "",
		flag: "https://restcountries.eu/data/atf.svg",
	},
	{
		name: "Gabon",
		capital: "Libreville",
		code: "241",
		flag: "https://restcountries.eu/data/gab.svg",
	},
	{
		name: "Gambia",
		capital: "Banjul",
		code: "220",
		flag: "https://restcountries.eu/data/gmb.svg",
	},
	{
		name: "Georgia",
		capital: "Tbilisi",
		code: "995",
		flag: "https://restcountries.eu/data/geo.svg",
	},
	{
		name: "Germany",
		capital: "Berlin",
		code: "49",
		flag: "https://restcountries.eu/data/deu.svg",
	},
	{
		name: "Ghana",
		capital: "Accra",
		code: "233",
		flag: "https://restcountries.eu/data/gha.svg",
	},
	{
		name: "Gibraltar",
		capital: "Gibraltar",
		code: "350",
		flag: "https://restcountries.eu/data/gib.svg",
	},
	{
		name: "Greece",
		capital: "Athens",
		code: "30",
		flag: "https://restcountries.eu/data/grc.svg",
	},
	{
		name: "Greenland",
		capital: "Nuuk",
		code: "299",
		flag: "https://restcountries.eu/data/grl.svg",
	},
	{
		name: "Grenada",
		capital: "St. George's",
		code: "1473",
		flag: "https://restcountries.eu/data/grd.svg",
	},
	{
		name: "Guadeloupe",
		capital: "Basse-Terre",
		code: "590",
		flag: "https://restcountries.eu/data/glp.svg",
	},
	{
		name: "Guam",
		capital: "Hagåtña",
		code: "1671",
		flag: "https://restcountries.eu/data/gum.svg",
	},
	{
		name: "Guatemala",
		capital: "Guatemala City",
		code: "502",
		flag: "https://restcountries.eu/data/gtm.svg",
	},
	{
		name: "Guernsey",
		capital: "St. Peter Port",
		code: "44",
		flag: "https://restcountries.eu/data/ggy.svg",
	},
	{
		name: "Guinea",
		capital: "Conakry",
		code: "224",
		flag: "https://restcountries.eu/data/gin.svg",
	},
	{
		name: "Guinea-Bissau",
		capital: "Bissau",
		code: "245",
		flag: "https://restcountries.eu/data/gnb.svg",
	},
	{
		name: "Guyana",
		capital: "Georgetown",
		code: "592",
		flag: "https://restcountries.eu/data/guy.svg",
	},
	{
		name: "Haiti",
		capital: "Port-au-Prince",
		code: "509",
		flag: "https://restcountries.eu/data/hti.svg",
	},
	{
		name: "Heard Island and McDonald Islands",
		capital: "",
		code: "",
		flag: "https://restcountries.eu/data/hmd.svg",
	},
	{
		name: "Holy See",
		capital: "Rome",
		code: "379",
		flag: "https://restcountries.eu/data/vat.svg",
	},
	{
		name: "Honduras",
		capital: "Tegucigalpa",
		code: "504",
		flag: "https://restcountries.eu/data/hnd.svg",
	},
	{
		name: "Hong Kong",
		capital: "City of Victoria",
		code: "852",
		flag: "https://restcountries.eu/data/hkg.svg",
	},
	{
		name: "Hungary",
		capital: "Budapest",
		code: "36",
		flag: "https://restcountries.eu/data/hun.svg",
	},
	{
		name: "Iceland",
		capital: "Reykjavík",
		code: "354",
		flag: "https://restcountries.eu/data/isl.svg",
	},
	{
		name: "India",
		capital: "New Delhi",
		code: "91",
		flag: "https://restcountries.eu/data/ind.svg",
	},
	{
		name: "Indonesia",
		capital: "Jakarta",
		code: "62",
		flag: "https://restcountries.eu/data/idn.svg",
	},
	{
		name: "Côte d'Ivoire",
		capital: "Yamoussoukro",
		code: "225",
		flag: "https://restcountries.eu/data/civ.svg",
	},
	{
		name: "Iran (Islamic Republic of)",
		capital: "Tehran",
		code: "98",
		flag: "https://restcountries.eu/data/irn.svg",
	},
	{
		name: "Iraq",
		capital: "Baghdad",
		code: "964",
		flag: "https://restcountries.eu/data/irq.svg",
	},
	{
		name: "Ireland",
		capital: "Dublin",
		code: "353",
		flag: "https://restcountries.eu/data/irl.svg",
	},
	{
		name: "Isle of Man",
		capital: "Douglas",
		code: "44",
		flag: "https://restcountries.eu/data/imn.svg",
	},
	{
		name: "Israel",
		capital: "Jerusalem",
		code: "972",
		flag: "https://restcountries.eu/data/isr.svg",
	},
	{
		name: "Italy",
		capital: "Rome",
		code: "39",
		flag: "https://restcountries.eu/data/ita.svg",
	},
	{
		name: "Jamaica",
		capital: "Kingston",
		code: "1876",
		flag: "https://restcountries.eu/data/jam.svg",
	},
	{
		name: "Japan",
		capital: "Tokyo",
		code: "81",
		flag: "https://restcountries.eu/data/jpn.svg",
	},
	{
		name: "Jersey",
		capital: "Saint Helier",
		code: "44",
		flag: "https://restcountries.eu/data/jey.svg",
	},
	{
		name: "Jordan",
		capital: "Amman",
		code: "962",
		flag: "https://restcountries.eu/data/jor.svg",
	},
	{
		name: "Kazakhstan",
		capital: "Astana",
		code: "76",
		flag: "https://restcountries.eu/data/kaz.svg",
	},
	{
		name: "Kenya",
		capital: "Nairobi",
		code: "254",
		flag: "https://restcountries.eu/data/ken.svg",
	},
	{
		name: "Kiribati",
		capital: "South Tarawa",
		code: "686",
		flag: "https://restcountries.eu/data/kir.svg",
	},
	{
		name: "Kuwait",
		capital: "Kuwait City",
		code: "965",
		flag: "https://restcountries.eu/data/kwt.svg",
	},
	{
		name: "Kyrgyzstan",
		capital: "Bishkek",
		code: "996",
		flag: "https://restcountries.eu/data/kgz.svg",
	},
	{
		name: "Lao People's Democratic Republic",
		capital: "Vientiane",
		code: "856",
		flag: "https://restcountries.eu/data/lao.svg",
	},
	{
		name: "Latvia",
		capital: "Riga",
		code: "371",
		flag: "https://restcountries.eu/data/lva.svg",
	},
	{
		name: "Lebanon",
		capital: "Beirut",
		code: "961",
		flag: "https://restcountries.eu/data/lbn.svg",
	},
	{
		name: "Lesotho",
		capital: "Maseru",
		code: "266",
		flag: "https://restcountries.eu/data/lso.svg",
	},
	{
		name: "Liberia",
		capital: "Monrovia",
		code: "231",
		flag: "https://restcountries.eu/data/lbr.svg",
	},
	{
		name: "Libya",
		capital: "Tripoli",
		code: "218",
		flag: "https://restcountries.eu/data/lby.svg",
	},
	{
		name: "Liechtenstein",
		capital: "Vaduz",
		code: "423",
		flag: "https://restcountries.eu/data/lie.svg",
	},
	{
		name: "Lithuania",
		capital: "Vilnius",
		code: "370",
		flag: "https://restcountries.eu/data/ltu.svg",
	},
	{
		name: "Luxembourg",
		capital: "Luxembourg",
		code: "352",
		flag: "https://restcountries.eu/data/lux.svg",
	},
	{
		name: "Macao",
		capital: "",
		code: "853",
		flag: "https://restcountries.eu/data/mac.svg",
	},
	{
		name: "Macedonia (the former Yugoslav Republic of)",
		capital: "Skopje",
		code: "389",
		flag: "https://restcountries.eu/data/mkd.svg",
	},
	{
		name: "Madagascar",
		capital: "Antananarivo",
		code: "261",
		flag: "https://restcountries.eu/data/mdg.svg",
	},
	{
		name: "Malawi",
		capital: "Lilongwe",
		code: "265",
		flag: "https://restcountries.eu/data/mwi.svg",
	},
	{
		name: "Malaysia",
		capital: "Kuala Lumpur",
		code: "60",
		flag: "https://restcountries.eu/data/mys.svg",
	},
	{
		name: "Maldives",
		capital: "Malé",
		code: "960",
		flag: "https://restcountries.eu/data/mdv.svg",
	},
	{
		name: "Mali",
		capital: "Bamako",
		code: "223",
		flag: "https://restcountries.eu/data/mli.svg",
	},
	{
		name: "Malta",
		capital: "Valletta",
		code: "356",
		flag: "https://restcountries.eu/data/mlt.svg",
	},
	{
		name: "Marshall Islands",
		capital: "Majuro",
		code: "692",
		flag: "https://restcountries.eu/data/mhl.svg",
	},
	{
		name: "Martinique",
		capital: "Fort-de-France",
		code: "596",
		flag: "https://restcountries.eu/data/mtq.svg",
	},
	{
		name: "Mauritania",
		capital: "Nouakchott",
		code: "222",
		flag: "https://restcountries.eu/data/mrt.svg",
	},
	{
		name: "Mauritius",
		capital: "Port Louis",
		code: "230",
		flag: "https://restcountries.eu/data/mus.svg",
	},
	{
		name: "Mayotte",
		capital: "Mamoudzou",
		code: "262",
		flag: "https://restcountries.eu/data/myt.svg",
	},
	{
		name: "Mexico",
		capital: "Mexico City",
		code: "52",
		flag: "https://restcountries.eu/data/mex.svg",
	},
	{
		name: "Micronesia (Federated States of)",
		capital: "Palikir",
		code: "691",
		flag: "https://restcountries.eu/data/fsm.svg",
	},
	{
		name: "Moldova (Republic of)",
		capital: "Chișinău",
		code: "373",
		flag: "https://restcountries.eu/data/mda.svg",
	},
	{
		name: "Monaco",
		capital: "Monaco",
		code: "377",
		flag: "https://restcountries.eu/data/mco.svg",
	},
	{
		name: "Mongolia",
		capital: "Ulan Bator",
		code: "976",
		flag: "https://restcountries.eu/data/mng.svg",
	},
	{
		name: "Montenegro",
		capital: "Podgorica",
		code: "382",
		flag: "https://restcountries.eu/data/mne.svg",
	},
	{
		name: "Montserrat",
		capital: "Plymouth",
		code: "1664",
		flag: "https://restcountries.eu/data/msr.svg",
	},
	{
		name: "Morocco",
		capital: "Rabat",
		code: "212",
		flag: "https://restcountries.eu/data/mar.svg",
	},
	{
		name: "Mozambique",
		capital: "Maputo",
		code: "258",
		flag: "https://restcountries.eu/data/moz.svg",
	},
	{
		name: "Myanmar",
		capital: "Naypyidaw",
		code: "95",
		flag: "https://restcountries.eu/data/mmr.svg",
	},
	{
		name: "Namibia",
		capital: "Windhoek",
		code: "264",
		flag: "https://restcountries.eu/data/nam.svg",
	},
	{
		name: "Nauru",
		capital: "Yaren",
		code: "674",
		flag: "https://restcountries.eu/data/nru.svg",
	},
	{
		name: "Nepal",
		capital: "Kathmandu",
		code: "977",
		flag: "https://restcountries.eu/data/npl.svg",
	},
	{
		name: "Netherlands",
		capital: "Amsterdam",
		code: "31",
		flag: "https://restcountries.eu/data/nld.svg",
	},
	{
		name: "New Caledonia",
		capital: "Nouméa",
		code: "687",
		flag: "https://restcountries.eu/data/ncl.svg",
	},
	{
		name: "New Zealand",
		capital: "Wellington",
		code: "64",
		flag: "https://restcountries.eu/data/nzl.svg",
	},
	{
		name: "Nicaragua",
		capital: "Managua",
		code: "505",
		flag: "https://restcountries.eu/data/nic.svg",
	},
	{
		name: "Niger",
		capital: "Niamey",
		code: "227",
		flag: "https://restcountries.eu/data/ner.svg",
	},
	{
		name: "Nigeria",
		capital: "Abuja",
		code: "234",
		flag: "https://restcountries.eu/data/nga.svg",
	},
	{
		name: "Niue",
		capital: "Alofi",
		code: "683",
		flag: "https://restcountries.eu/data/niu.svg",
	},
	{
		name: "Norfolk Island",
		capital: "Kingston",
		code: "672",
		flag: "https://restcountries.eu/data/nfk.svg",
	},
	{
		name: "Korea (Democratic People's Republic of)",
		capital: "Pyongyang",
		code: "850",
		flag: "https://restcountries.eu/data/prk.svg",
	},
	{
		name: "Northern Mariana Islands",
		capital: "Saipan",
		code: "1670",
		flag: "https://restcountries.eu/data/mnp.svg",
	},
	{
		name: "Norway",
		capital: "Oslo",
		code: "47",
		flag: "https://restcountries.eu/data/nor.svg",
	},
	{
		name: "Oman",
		capital: "Muscat",
		code: "968",
		flag: "https://restcountries.eu/data/omn.svg",
	},
	{
		name: "Pakistan",
		capital: "Islamabad",
		code: "92",
		flag: "https://restcountries.eu/data/pak.svg",
	},
	{
		name: "Palau",
		capital: "Ngerulmud",
		code: "680",
		flag: "https://restcountries.eu/data/plw.svg",
	},
	{
		name: "Palestine, State of",
		capital: "Ramallah",
		code: "970",
		flag: "https://restcountries.eu/data/pse.svg",
	},
	{
		name: "Panama",
		capital: "Panama City",
		code: "507",
		flag: "https://restcountries.eu/data/pan.svg",
	},
	{
		name: "Papua New Guinea",
		capital: "Port Moresby",
		code: "675",
		flag: "https://restcountries.eu/data/png.svg",
	},
	{
		name: "Paraguay",
		capital: "Asunción",
		code: "595",
		flag: "https://restcountries.eu/data/pry.svg",
	},
	{
		name: "Peru",
		capital: "Lima",
		code: "51",
		flag: "https://restcountries.eu/data/per.svg",
	},
	{
		name: "Philippines",
		capital: "Manila",
		code: "63",
		flag: "https://restcountries.eu/data/phl.svg",
	},
	{
		name: "Pitcairn",
		capital: "Adamstown",
		code: "64",
		flag: "https://restcountries.eu/data/pcn.svg",
	},
	{
		name: "Poland",
		capital: "Warsaw",
		code: "48",
		flag: "https://restcountries.eu/data/pol.svg",
	},
	{
		name: "Portugal",
		capital: "Lisbon",
		code: "351",
		flag: "https://restcountries.eu/data/prt.svg",
	},
	{
		name: "Puerto Rico",
		capital: "San Juan",
		code: "1787",
		flag: "https://restcountries.eu/data/pri.svg",
	},
	{
		name: "Qatar",
		capital: "Doha",
		code: "974",
		flag: "https://restcountries.eu/data/qat.svg",
	},
	{
		name: "Republic of Kosovo",
		capital: "Pristina",
		code: "383",
		flag: "https://restcountries.eu/data/kos.svg",
	},
	{
		name: "Réunion",
		capital: "Saint-Denis",
		code: "262",
		flag: "https://restcountries.eu/data/reu.svg",
	},
	{
		name: "Romania",
		capital: "Bucharest",
		code: "40",
		flag: "https://restcountries.eu/data/rou.svg",
	},
	{
		name: "Russian Federation",
		capital: "Moscow",
		code: "7",
		flag: "https://restcountries.eu/data/rus.svg",
	},
	{
		name: "Rwanda",
		capital: "Kigali",
		code: "250",
		flag: "https://restcountries.eu/data/rwa.svg",
	},
	{
		name: "Saint Barthélemy",
		capital: "Gustavia",
		code: "590",
		flag: "https://restcountries.eu/data/blm.svg",
	},
	{
		name: "Saint Helena, Ascension and Tristan da Cunha",
		capital: "Jamestown",
		code: "290",
		flag: "https://restcountries.eu/data/shn.svg",
	},
	{
		name: "Saint Kitts and Nevis",
		capital: "Basseterre",
		code: "1869",
		flag: "https://restcountries.eu/data/kna.svg",
	},
	{
		name: "Saint Lucia",
		capital: "Castries",
		code: "1758",
		flag: "https://restcountries.eu/data/lca.svg",
	},
	{
		name: "Saint Martin (French part)",
		capital: "Marigot",
		code: "590",
		flag: "https://restcountries.eu/data/maf.svg",
	},
	{
		name: "Saint Pierre and Miquelon",
		capital: "Saint-Pierre",
		code: "508",
		flag: "https://restcountries.eu/data/spm.svg",
	},
	{
		name: "Saint Vincent and the Grenadines",
		capital: "Kingstown",
		code: "1784",
		flag: "https://restcountries.eu/data/vct.svg",
	},
	{
		name: "Samoa",
		capital: "Apia",
		code: "685",
		flag: "https://restcountries.eu/data/wsm.svg",
	},
	{
		name: "San Marino",
		capital: "City of San Marino",
		code: "378",
		flag: "https://restcountries.eu/data/smr.svg",
	},
	{
		name: "Sao Tome and Principe",
		capital: "São Tomé",
		code: "239",
		flag: "https://restcountries.eu/data/stp.svg",
	},
	{
		name: "Saudi Arabia",
		capital: "Riyadh",
		code: "966",
		flag: "https://restcountries.eu/data/sau.svg",
	},
	{
		name: "Senegal",
		capital: "Dakar",
		code: "221",
		flag: "https://restcountries.eu/data/sen.svg",
	},
	{
		name: "Serbia",
		capital: "Belgrade",
		code: "381",
		flag: "https://restcountries.eu/data/srb.svg",
	},
	{
		name: "Seychelles",
		capital: "Victoria",
		code: "248",
		flag: "https://restcountries.eu/data/syc.svg",
	},
	{
		name: "Sierra Leone",
		capital: "Freetown",
		code: "232",
		flag: "https://restcountries.eu/data/sle.svg",
	},
	{
		name: "Singapore",
		capital: "Singapore",
		code: "65",
		flag: "https://restcountries.eu/data/sgp.svg",
	},
	{
		name: "Sint Maarten (Dutch part)",
		capital: "Philipsburg",
		code: "1721",
		flag: "https://restcountries.eu/data/sxm.svg",
	},
	{
		name: "Slovakia",
		capital: "Bratislava",
		code: "421",
		flag: "https://restcountries.eu/data/svk.svg",
	},
	{
		name: "Slovenia",
		capital: "Ljubljana",
		code: "386",
		flag: "https://restcountries.eu/data/svn.svg",
	},
	{
		name: "Solomon Islands",
		capital: "Honiara",
		code: "677",
		flag: "https://restcountries.eu/data/slb.svg",
	},
	{
		name: "Somalia",
		capital: "Mogadishu",
		code: "252",
		flag: "https://restcountries.eu/data/som.svg",
	},
	{
		name: "South Africa",
		capital: "Pretoria",
		code: "27",
		flag: "https://restcountries.eu/data/zaf.svg",
	},
	{
		name: "South Georgia and the South Sandwich Islands",
		capital: "King Edward Point",
		code: "500",
		flag: "https://restcountries.eu/data/sgs.svg",
	},
	{
		name: "Korea (Republic of)",
		capital: "Seoul",
		code: "82",
		flag: "https://restcountries.eu/data/kor.svg",
	},
	{
		name: "South Sudan",
		capital: "Juba",
		code: "211",
		flag: "https://restcountries.eu/data/ssd.svg",
	},
	{
		name: "Spain",
		capital: "Madrid",
		code: "34",
		flag: "https://restcountries.eu/data/esp.svg",
	},
	{
		name: "Sri Lanka",
		capital: "Colombo",
		code: "94",
		flag: "https://restcountries.eu/data/lka.svg",
	},
	{
		name: "Sudan",
		capital: "Khartoum",
		code: "249",
		flag: "https://restcountries.eu/data/sdn.svg",
	},
	{
		name: "Suriname",
		capital: "Paramaribo",
		code: "597",
		flag: "https://restcountries.eu/data/sur.svg",
	},
	{
		name: "Svalbard and Jan Mayen",
		capital: "Longyearbyen",
		code: "4779",
		flag: "https://restcountries.eu/data/sjm.svg",
	},
	{
		name: "Swaziland",
		capital: "Lobamba",
		code: "268",
		flag: "https://restcountries.eu/data/swz.svg",
	},
	{
		name: "Sweden",
		capital: "Stockholm",
		code: "46",
		flag: "https://restcountries.eu/data/swe.svg",
	},
	{
		name: "Switzerland",
		capital: "Bern",
		code: "41",
		flag: "https://restcountries.eu/data/che.svg",
	},
	{
		name: "Syrian Arab Republic",
		capital: "Damascus",
		code: "963",
		flag: "https://restcountries.eu/data/syr.svg",
	},
	{
		name: "Taiwan",
		capital: "Taipei",
		code: "886",
		flag: "https://restcountries.eu/data/twn.svg",
	},
	{
		name: "Tajikistan",
		capital: "Dushanbe",
		code: "992",
		flag: "https://restcountries.eu/data/tjk.svg",
	},
	{
		name: "Tanzania, United Republic of",
		capital: "Dodoma",
		code: "255",
		flag: "https://restcountries.eu/data/tza.svg",
	},
	{
		name: "Thailand",
		capital: "Bangkok",
		code: "66",
		flag: "https://restcountries.eu/data/tha.svg",
	},
	{
		name: "Timor-Leste",
		capital: "Dili",
		code: "670",
		flag: "https://restcountries.eu/data/tls.svg",
	},
	{
		name: "Togo",
		capital: "Lomé",
		code: "228",
		flag: "https://restcountries.eu/data/tgo.svg",
	},
	{
		name: "Tokelau",
		capital: "Fakaofo",
		code: "690",
		flag: "https://restcountries.eu/data/tkl.svg",
	},
	{
		name: "Tonga",
		capital: "Nuku'alofa",
		code: "676",
		flag: "https://restcountries.eu/data/ton.svg",
	},
	{
		name: "Trinidad and Tobago",
		capital: "Port of Spain",
		code: "1868",
		flag: "https://restcountries.eu/data/tto.svg",
	},
	{
		name: "Tunisia",
		capital: "Tunis",
		code: "216",
		flag: "https://restcountries.eu/data/tun.svg",
	},
	{
		name: "Turkey",
		capital: "Ankara",
		code: "90",
		flag: "https://restcountries.eu/data/tur.svg",
	},
	{
		name: "Turkmenistan",
		capital: "Ashgabat",
		code: "993",
		flag: "https://restcountries.eu/data/tkm.svg",
	},
	{
		name: "Turks and Caicos Islands",
		capital: "Cockburn Town",
		code: "1649",
		flag: "https://restcountries.eu/data/tca.svg",
	},
	{
		name: "Tuvalu",
		capital: "Funafuti",
		code: "688",
		flag: "https://restcountries.eu/data/tuv.svg",
	},
	{
		name: "Uganda",
		capital: "Kampala",
		code: "256",
		flag: "https://restcountries.eu/data/uga.svg",
	},
	{
		name: "Ukraine",
		capital: "Kyiv",
		code: "380",
		flag: "https://restcountries.eu/data/ukr.svg",
	},
	{
		name: "United Arab Emirates",
		capital: "Abu Dhabi",
		code: "971",
		flag: "https://restcountries.eu/data/are.svg",
	},
	{
		name: "United Kingdom of Great Britain and Northern Ireland",
		capital: "London",
		code: "44",
		flag: "https://restcountries.eu/data/gbr.svg",
	},
	{
		name: "United States of America",
		capital: "Washington, D.C.",
		code: "1",
		flag: "https://restcountries.eu/data/usa.svg",
	},
	{
		name: "Uruguay",
		capital: "Montevideo",
		code: "598",
		flag: "https://restcountries.eu/data/ury.svg",
	},
	{
		name: "Uzbekistan",
		capital: "Tashkent",
		code: "998",
		flag: "https://restcountries.eu/data/uzb.svg",
	},
	{
		name: "Vanuatu",
		capital: "Port Vila",
		code: "678",
		flag: "https://restcountries.eu/data/vut.svg",
	},
	{
		name: "Venezuela (Bolivarian Republic of)",
		capital: "Caracas",
		code: "58",
		flag: "https://restcountries.eu/data/ven.svg",
	},
	{
		name: "Viet Nam",
		capital: "Hanoi",
		code: "84",
		flag: "https://restcountries.eu/data/vnm.svg",
	},
	{
		name: "Virgin Islands (British)",
		capital: "Road Town",
		code: "1284",
		flag: "https://restcountries.eu/data/vgb.svg",
	},
	{
		name: "Virgin Islands (U.S.)",
		capital: "Charlotte Amalie",
		code: "1 340",
		flag: "https://restcountries.eu/data/vir.svg",
	},

	{
		name: "Western Sahara",
		capital: "El Aaiún",
		code: "212",
		flag: "https://restcountries.eu/data/esh.svg",
	},
	{
		name: "Yemen",
		capital: "Sana'a",
		code: "967",
		flag: "https://restcountries.eu/data/yem.svg",
	},
	{
		name: "Zambia",
		capital: "Lusaka",
		code: "260",
		flag: "https://restcountries.eu/data/zmb.svg",
	},
	{
		name: "Zimbabwe",
		capital: "Harare",
		code: "263",
		flag: "https://restcountries.eu/data/zwe.svg",
	},
	{
		name: "Åland Islands",
		capital: "Mariehamn",
		code: "358",
		flag: "https://restcountries.eu/data/ala.svg",
	},
];
